In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Read csv file into a pandas dataframe
df = pd.read_csv(r'C:\Users\maria\Documents\MARIA\BioMed\FIRST_SEMESTER\Î‘Î™\clinical_dataset.csv',delimiter=';')
# Take a look at the first few rows
df.head(10)
#print(df)

,part_id,fried,gender,age,hospitalization_one_year,hospitalization_three_years,ortho_hypotension,vision,audition,weight_loss,...,health_rate_comparison,pain_perception,activity_regular,smoking,alcohol_units,katz_index,iadl_grade,comorbidities_count,comorbidities_significant_count,medication_count
0,1001,Non frail,F,75,0,0,No,Sees moderately,Hears well,No,...,3 - About the same,4.2,> 2 h and < 5 h per week,Never smoked,1.0,6.0,31.0,5,0,5
1,1002,Pre-frail,M,73,0,1,No,Sees moderately,Hears moderately,No,...,2 - A little worse,3.3,> 2 h and < 5 h per week,Never smoked,14.0,6.0,26.0,12,0,4
2,1003,Pre-frail,M,72,0,0,No,Sees moderately,Hears moderately,No,...,3 - About the same,3.4,< 2 h per week,Past smoker (stopped at least 6 months),21.0,6.0,26.0,9,0,3
3,1004,Frail,F,88,0,0,No,Sees moderately,Hears moderately,No,...,3 - About the same,7.3,< 2 h per week,Never smoked,21.0,5.5,20.0,11,0,8
4,1005,Pre-frail,F,83,0,4,Yes,Sees moderately,Hears poorly,No,...,3 - About the same,3.0,> 5 h per week,Current smoker,0.0,6.0,30.0,12,0,4
5,1006,Non frail,M,72,0,1,No,Sees moderately,Hears well,No,...,3 - About the same,0.0,> 2 h and < 5 h per week,Never smoked,7.0,6.0,28.0,5,0,6
6,1007,Non frail,F,70,0,0,No,Sees moderately,Hears well,No,...,3 - About the same,2.4,> 2 h and < 5 h per week,Current smoker,0.0,6.0,31.0,4,0,2
7,1008,Frail,F,74,10,11,No,Sees moderately,Hears moderately,Yes,...,4 - A little better,5.0,> 2 h and < 5 h per week,Never smoked,0.0,5.0,25.0,8,2,2
8,1009,Pre-frail,F,76,0,1,No,Sees moderately,Hears well,No,...,2 - A little worse,2.0,> 5 h per week,Never smoked,0.0,6.0,31.0,10,0,6
9,1010,Frail,F,72,0,2,No,Sees moderately,Hears well,Yes,...,2 - A little worse,5.0,< 2 h per week,Past smoker (stopped at least 6 months),10.5,2.5,18.0,9,1,7

In [2]:
# information for data 
from sklearn import preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 55 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   part_id                          540 non-null    int64
 1   fried                            540 non-null    object
 2   gender                           540 non-null    object
 3   age                              540 non-null    int64
 4   hospitalization_one_year         540 non-null    int64
 5   hospitalization_three_years      540 non-null    int64
 6   ortho_hypotension                540 non-null    object
 7   vision                           540 non-null    object
 8   audition                         540 non-null    object
 9   weight_loss                      538 non-null    object
 10  exhaustion_score                 540 non-null    int64
 11  raise_chair_time                 539 non-null    float64
 12  balance_single                   539 non-null    object
 13  gait_get_up                      538 non-null    float64
 14  gait_speed_4m                    540 non-null    float64
 15  gait_optional_binary             540 non-null    bool
 16  gait_speed_slower                540 non-null    object
 17  grip_strength_abnormal           540 non-null    object
 18  low_physical_activity            540 non-null    object
 19  falls_one_year                   540 non-null    int64
 20  fractures_three_years            540 non-null    int64
 21  bmi_score                        538 non-null    float64
 22  bmi_body_fat                     407 non-null    float64
 23  waist                            537 non-null    float64
 24  lean_body_mass                   407 non-null    float64
 25  screening_score                  540 non-null    int64
 26  cognitive_total_score            484 non-null    float64
 27  memory_complain                  501 non-null    object
 28  sleep                            537 non-null    object
 29  mmse_total_score                 540 non-null    int64
 30  depression_total_score           539 non-null    float64
 31  anxiety_perception               539 non-null    float64
 32  living_alone                     539 non-null    object
 33  leisure_out                      539 non-null    float64
 34  leisure_club                     539 non-null    object
 35  social_visits                    539 non-null    float64
 36  social_calls                     538 non-null    float64
 37  social_phone                     539 non-null    float64
 38  social_skype                     539 non-null    float64
 39  social_text                      538 non-null    float64
 40  house_suitable_participant       442 non-null    object
 41  house_suitable_professional      442 non-null    object
 42  stairs_number                    442 non-null    float64
 43  life_quality                     539 non-null    float64
 44  health_rate                      539 non-null    object
 45  health_rate_comparison           539 non-null    object
 46  pain_perception                  539 non-null    float64
 47  activity_regular                 538 non-null    object
 48  smoking                          539 non-null    object
 49  alcohol_units                    540 non-null    float64
 50  katz_index                       540 non-null    float64
 51  iadl_grade                       539 non-null    float64
 52  comorbidities_count              540 non-null    int64
 53  comorbidities_significant_count  540 non-null    int64
 54  medication_count                 540 non-null    int64
dtypes: bool(1), float64(22), int64(12), object(20)
memory usage: 228.5+ KB

In [3]:
# Convert nominal features to numerical
df['fried'].replace(['Frail', 'Pre-frail','Non frail'],
                        [2, 1,0], inplace=True)
df['gender'].replace(['F','M'],
                        [1,0], inplace=True)
df['ortho_hypotension'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['vision'].replace(['Sees well','Sees moderately','Sees poorly'],
                        [2,1,0], inplace=True)
df['audition'].replace(['Hears well','Hears moderately','Hears poorly'],
                        [2,1,0], inplace=True)
df['weight_loss'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['balance_single'].replace(['>5 sec','<5 sec','test non realizable'],
                        [2,1,0], inplace=True)
df['gait_speed_slower'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['grip_strength_abnormal'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['low_physical_activity'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['memory_complain'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['sleep'].replace(['Permanent sleep problem','Occasional sleep problem','No sleep problem'],
                        [2,1,0], inplace=True)
df['living_alone'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['leisure_club'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['house_suitable_participant'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['house_suitable_professional'].replace(['Yes','No'],
                        [1,0], inplace=True)
df['health_rate'].replace(['5-Excellent','4-Good','3 - Medium','2 - Bad','1 - Very bad'],
                        [5,4,3,2,1], inplace=True)
df['health_rate_comparison'].replace(['5 - A lot better','4 - A little better','3 - About the same','2 - A little worse','1 - A lot worse'],
                        [5,4,3,2,1], inplace=True)
df['activity_regular'].replace(['> 5 h per week','> 2 h and < 5 h per week','< 2 h per week','No'],
                        [3,2,1,0], inplace=True)
df['smoking'].replace(['Current smoker','Past smoker (stopped at least 6 months)','Never smoked'],
                        [2,1,0], inplace=True)

#print(df)
df.head()

,part_id,fried,gender,age,hospitalization_one_year,hospitalization_three_years,ortho_hypotension,vision,audition,weight_loss,...,health_rate_comparison,pain_perception,activity_regular,smoking,alcohol_units,katz_index,iadl_grade,comorbidities_count,comorbidities_significant_count,medication_count
0,1001,0,1,75,0,0,0,1,2,0.0,...,3.0,4.2,2.0,0.0,1.0,6.0,31.0,5,0,5
1,1002,1,0,73,0,1,0,1,1,0.0,...,2.0,3.3,2.0,0.0,14.0,6.0,26.0,12,0,4
2,1003,1,0,72,0,0,0,1,1,0.0,...,3.0,3.4,1.0,1.0,21.0,6.0,26.0,9,0,3
3,1004,2,1,88,0,0,0,1,1,0.0,...,3.0,7.3,1.0,0.0,21.0,5.5,20.0,11,0,8
4,1005,1,1,83,0,4,1,1,0,0.0,...,3.0,3.0,3.0,2.0,0.0,6.0,30.0,12,0,4

In [4]:
# test collumn
print (df['raise_chair_time'])
print (df['raise_chair_time'].isnull())

0       13.00
1       16.00
2       10.00
3      999.00
4       13.00
        ...
535     14.00
536     14.80
537      6.59
538     11.10
539      6.60
Name: raise_chair_time, Length: 540, dtype: float64
0      False
1      False
2      False
3      False
4      False
       ...
535    False
536    False
537    False
538    False
539    False
Name: raise_chair_time, Length: 540, dtype: bool

In [6]:
print (df.isnull().sum())

part_id                              0
fried                                0
gender                               0
age                                  0
hospitalization_one_year             0
hospitalization_three_years          0
ortho_hypotension                    0
vision                               0
audition                             0
weight_loss                          2
exhaustion_score                     0
raise_chair_time                     1
balance_single                       1
gait_get_up                          2
gait_speed_4m                        0
gait_optional_binary                 0
gait_speed_slower                    0
grip_strength_abnormal               0
low_physical_activity                0
falls_one_year                       0
fractures_three_years                0
bmi_score                            2
bmi_body_fat                       133
waist                                3
lean_body_mass                     133
screening_score                      0
cognitive_total_score               56
memory_complain                     39
sleep                                3
mmse_total_score                     0
depression_total_score               1
anxiety_perception                   1
living_alone                         1
leisure_out                          1
leisure_club                         1
social_visits                        1
social_calls                         2
social_phone                         1
social_skype                         1
social_text                          2
house_suitable_participant          98
house_suitable_professional         98
stairs_number                       98
life_quality                         1
health_rate                          1
health_rate_comparison               1
pain_perception                      1
activity_regular                     2
smoking                              1
alcohol_units                        0
katz_index                           0
iadl_grade                           1
comorbidities_count                  0
comorbidities_significant_count      0
medication_count                     0
dtype: int64

In [7]:
print(df.columns)

Index(['part_id', 'fried', 'gender', 'age', 'hospitalization_one_year',
       'hospitalization_three_years', 'ortho_hypotension', 'vision',
       'audition', 'weight_loss', 'exhaustion_score', 'raise_chair_time',
       'balance_single', 'gait_get_up', 'gait_speed_4m',
       'gait_optional_binary', 'gait_speed_slower', 'grip_strength_abnormal',
       'low_physical_activity', 'falls_one_year', 'fractures_three_years',
       'bmi_score', 'bmi_body_fat', 'waist', 'lean_body_mass',
       'screening_score', 'cognitive_total_score', 'memory_complain', 'sleep',
       'mmse_total_score', 'depression_total_score', 'anxiety_perception',
       'living_alone', 'leisure_out', 'leisure_club', 'social_visits',
       'social_calls', 'social_phone', 'social_skype', 'social_text',
       'house_suitable_participant', 'house_suitable_professional',
       'stairs_number', 'life_quality', 'health_rate',
       'health_rate_comparison', 'pain_perception', 'activity_regular',
       'smoking', 'alcohol_units', 'katz_index', 'iadl_grade',
       'comorbidities_count', 'comorbidities_significant_count',
       'medication_count'],
      dtype='object')

In [4]:
# Remove erroneous values
for i in df.columns:
    for j in range (len(df[i])):
        if df[i][j]==999 or type(df[i][j]).__name__=='str':
            df.at[j,i]=None
        # df[i][j]=None
print (df['raise_chair_time'])

0      13.00
1      16.00
2      10.00
3        NaN
4      13.00
       ...
535    14.00
536    14.80
537     6.59
538    11.10
539     6.60
Name: raise_chair_time, Length: 540, dtype: float64

In [5]:
# Handle missing values
for i in df.columns:
    mean=df[i].mean(skipna=True)
    for j in range (len(df[i])):
        if pd.isna(df[i][j]):df.at[j,i]=mean
print (df['raise_chair_time'])  




#for i in df.columns:
    #mean=df[i].mean(skipna=True)
    #df[i].replace(['NaN'],
                      #  [mean], inplace=True)

0      13.000000
1      16.000000
2      10.000000
3      13.471636
4      13.000000
         ...
535    14.000000
536    14.800000
537     6.590000
538    11.100000
539     6.600000
Name: raise_chair_time, Length: 540, dtype: float64

In [38]:
df.gait_speed_slower.head(20)

0     0.000000
1     1.000000
2     1.000000
3     1.000000
4     1.000000
5     0.000000
6     0.000000
7     1.000000
8     1.000000
9     0.277985
10    1.000000
11    0.000000
12    0.000000
13    1.000000
14    0.000000
15    1.000000
16    1.000000
17    1.000000
18    1.000000
19    0.277985
Name: gait_speed_slower, dtype: float64

In [6]:
def calculate_prior(df, Y):
    classes = sorted(list(df[Y].unique()))
    prior = []
    for i in classes:
        prior.append(len(df[df[Y]==i])/len(df))
    return prior

In [7]:
def calculate_likelihood_categorical(df, feat_name, feat_val, Y, label):
    feat = list(df.columns)
    df = df[df[Y]==label]
    p_x_given_y = len(df[df[feat_name]==feat_val]) / len(df)
    return p_x_given_y

In [8]:
def naive_bayes_categorical(df, X, Y):
    # get feature names
    features = list(df.columns)
    features.remove(Y)
    # calculate prior
    prior = calculate_prior(df, Y)

    Y_pred = []
    # loop over every data sample
    for x in X:
        # calculate likelihood
        labels = sorted(list(df[Y].unique()))
        likelihood = [1]*len(labels)
        for j in range(len(labels)):
            for i in range(len(features)):
                likelihood[j] *= calculate_likelihood_categorical(df, features[i], x[i], Y, labels[j])

        # calculate posterior probability (numerator only)
        post_prob = [1]*len(labels)
        for j in range(len(labels)):
            post_prob[j] = likelihood[j] * prior[j]

        Y_pred.append(np.argmax(post_prob))

    return np.array(Y_pred)

In [9]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=.3, random_state=41)
new_train=df.loc[:,df.columns!='weight_loss']
new_train=new_train.loc[:,new_train.columns!='exhaustion_score']
new_train=new_train.loc[:,new_train.columns!='gait_speed_slower']
new_train=new_train.loc[:,new_train.columns!='grip_strength_abnormal']
new_train=new_train.loc[:,new_train.columns!='low_physical_activity']
ind=[]
for i in range(len(train.columns)):
    ind.append(i)
ind.remove(1) 
ind.remove(9)
ind.remove(10)
ind.remove(16)
ind.remove(17)
ind.remove(18)
X_test = test.iloc[:,ind].values
Y_test = test.iloc[:,1].values
Y_pred = naive_bayes_categorical(new_train, X=X_test, Y="fried")
labels=[0,1,2]
from sklearn.metrics import confusion_matrix, f1_score
print(confusion_matrix(Y_test, Y_pred,labels=labels))
print(f1_score(Y_test, Y_pred,average='weighted'))

[[60  0  0]
 [ 0 80  0]
 [ 0  0 22]]
1.0

In [10]:
print(Y_pred)

[0 1 2 2 0 1 1 0 1 0 1 1 0 0 1 0 1 1 2 0 1 2 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1
 0 0 1 0 0 0 1 1 0 1 0 0 1 0 2 1 1 1 2 1 0 1 2 0 0 1 1 2 1 0 1 1 2 0 1 0 1
 1 1 1 1 2 1 1 0 2 0 1 1 2 1 1 1 1 0 0 1 0 2 0 0 0 1 1 0 0 1 1 1 0 0 1 0 2
 0 1 2 0 0 1 0 1 1 1 1 1 1 2 1 1 2 0 2 0 0 1 2 1 2 0 1 1 1 1 0 1 1 0 1 1 1
 0 2 1 0 0 1 1 2 1 0 0 0 1 1]

In [34]:
print(Y_test)

[0 1 2 2 0 1 1 0 1 0 1 1 0 0 1 0 1 1 2 0 1 2 0 1 0 0 0 1 1 0 0 0 1 0 1 1 1
 0 0 1 0 0 0 1 1 0 1 0 0 1 0 2 1 1 1 2 1 0 1 2 0 0 1 1 2 1 0 1 1 2 0 1 0 1
 1 1 1 1 2 1 1 0 2 0 1 1 2 1 1 1 1 0 0 1 0 2 0 0 0 1 1 0 0 1 1 1 0 0]

In [10]:
df.head(10)

,part_id,fried,gender,age,hospitalization_one_year,hospitalization_three_years,ortho_hypotension,vision,audition,weight_loss,...,health_rate_comparison,pain_perception,activity_regular,smoking,alcohol_units,katz_index,iadl_grade,comorbidities_count,comorbidities_significant_count,medication_count
0,1001,0,1,75,0,0.0,0,1,2,0.0,...,3.0,4.2,2.0,0.0,1.0,6.0,31.0,5,0,5
1,1002,1,0,73,0,1.0,0,1,1,0.0,...,2.0,3.3,2.0,0.0,14.0,6.0,26.0,12,0,4
2,1003,1,0,72,0,0.0,0,1,1,0.0,...,3.0,3.4,1.0,1.0,21.0,6.0,26.0,9,0,3
3,1004,2,1,88,0,0.0,0,1,1,0.0,...,3.0,7.3,1.0,0.0,21.0,5.5,20.0,11,0,8
4,1005,1,1,83,0,4.0,1,1,0,0.0,...,3.0,3.0,3.0,2.0,0.0,6.0,30.0,12,0,4
5,1006,0,0,72,0,1.0,0,1,2,0.0,...,3.0,0.0,2.0,0.0,7.0,6.0,28.0,5,0,6
6,1007,0,1,70,0,0.0,0,1,2,0.0,...,3.0,2.4,2.0,2.0,0.0,6.0,31.0,4,0,2
7,1008,2,1,74,10,11.0,0,1,1,1.0,...,4.0,5.0,2.0,0.0,0.0,5.0,25.0,8,2,2
8,1009,1,1,76,0,1.0,0,1,2,0.0,...,2.0,2.0,3.0,0.0,0.0,6.0,31.0,10,0,6
9,1010,2,1,72,0,2.0,0,1,2,1.0,...,2.0,5.0,1.0,1.0,10.5,2.5,18.0,9,1,7

In [11]:
clinical_df=df

,part_id,fried,gender,age,hospitalization_one_year,hospitalization_three_years,ortho_hypotension,vision,audition,weight_loss,...,health_rate_comparison,pain_perception,activity_regular,smoking,alcohol_units,katz_index,iadl_grade,comorbidities_count,comorbidities_significant_count,medication_count
0,1001,0,1,75,0,0.0,0,1,2,0.0,...,3.0,4.2,2.0,0.0,1.0,6.0,31.0,5,0,5
1,1002,1,0,73,0,1.0,0,1,1,0.0,...,2.0,3.3,2.0,0.0,14.0,6.0,26.0,12,0,4
2,1003,1,0,72,0,0.0,0,1,1,0.0,...,3.0,3.4,1.0,1.0,21.0,6.0,26.0,9,0,3
3,1004,2,1,88,0,0.0,0,1,1,0.0,...,3.0,7.3,1.0,0.0,21.0,5.5,20.0,11,0,8
4,1005,1,1,83,0,4.0,1,1,0,0.0,...,3.0,3.0,3.0,2.0,0.0,6.0,30.0,12,0,4
5,1006,0,0,72,0,1.0,0,1,2,0.0,...,3.0,0.0,2.0,0.0,7.0,6.0,28.0,5,0,6
6,1007,0,1,70,0,0.0,0,1,2,0.0,...,3.0,2.4,2.0,2.0,0.0,6.0,31.0,4,0,2
7,1008,2,1,74,10,11.0,0,1,1,1.0,...,4.0,5.0,2.0,0.0,0.0,5.0,25.0,8,2,2
8,1009,1,1,76,0,1.0,0,1,2,0.0,...,2.0,2.0,3.0,0.0,0.0,6.0,31.0,10,0,6
9,1010,2,1,72,0,2.0,0,1,2,1.0,...,2.0,5.0,1.0,1.0,10.5,2.5,18.0,9,1,7

In [12]:
# Importing libraries
import pandas as pd
# Read csv file into a pandas dataframe
df = pd.read_csv(r'C:\Users\maria\Documents\MARIA\BioMed\FIRST_SEMESTER\Î‘Î™\beacons_dataset.csv',delimiter=';')
# Take a look at the first few rows
df.head(10)

  part_id   ts_date   ts_time     room
0    3089  20170915  06:45:22  Kitchen
1    3089  20170915  06:45:33  Bedroom
2    3089  20170915  06:45:39  Outdoor
3    3089  20170915  06:45:53  Bedroom
4    3089  20170915  06:46:09  Outdoor
5    3089  20170915  06:46:23  Bedroom
6    3089  20170915  06:46:39  Outdoor
7    3089  20170915  06:46:53  Bedroom
8    3089  20170915  06:47:09  Outdoor
9    3089  20170915  06:47:23  Bedroom

In [13]:
# different categories for room column
df['room'].value_counts().index
# rename categories
df= df.replace(dict.fromkeys(['Bedroom1','Bedroom2','Chambre','Bedroom1st','Bedroom-1','2ndRoom','Bed','bedroom'], 'Bedroom'))
df= df.replace(dict.fromkeys(['Kitcen','Kitvhen', 'Kitchen2', 'Kitcheb','Kiychen', 'Kitch', 'Kithen','kitchen','Kichen'], 'Kitchen'))
df= df.replace(dict.fromkeys(['Leavingroom','Sittingroom','SittingRoom','LivingRoom', 'Livingroom1', 'Livingroom2', 'SittingOver','LuvingRoom', 'SeatingRoom','Living','LivibgRoom','Livroom','livingroom','Livingroon','Leavivinroom','TV','Sittigroom',
       'Luvingroom1','LivingRoom2', 'Sittinroom','Liningroom', 'Sitingroom', 'LeavingRoom'], 'Livingroom'))
df= df.replace(dict.fromkeys(['DinerRoom','Dinerroom','DiningRoom','DinningRoom'], 'DinnerRoom'))
df= df.replace(dict.fromkeys(['Desk','Office-2','Office1','Workroom','Office1st','Office2'], 'Office'))
df= df.replace(dict.fromkeys(['ExitHall'], 'Hall'))
df= df.replace(dict.fromkeys(['Entry'], 'Entrance'))
df= df.replace(dict.fromkeys(['Garage','Pantry'], 'Storage'))
df= df.replace(dict.fromkeys(['Bathroom1','Baghroom','Bathroom-1','Washroom','Bqthroom','Bathroim', 'Bsthroom','Bathroon','Barhroom',], 'Bathroom'))
df= df.replace(dict.fromkeys(['Veranda','Guard','Garden'], 'Outdoor'))
df= df.replace(dict.fromkeys(['Box', 'One','Two','Box-1','Four','Right','Three','three','Left', 'K','T' ], 'Other'))
df= df.replace(dict.fromkeys(['LaundryRoom'], 'Laundry'))

In [14]:
# Define a function to check if a string is a 4-digit number
def is_4_digit(s):
    try:
        int(s)
        return len(s) == 4
    except ValueError:
        return False

# Use the function to filter the 'part_id' column
df = df[df['part_id'].apply(is_4_digit)]

# Print the resulting DataFrame
print(df)

      part_id   ts_date   ts_time        room
0        3089  20170915  06:45:22     Kitchen
1        3089  20170915  06:45:33     Bedroom
2        3089  20170915  06:45:39     Outdoor
3        3089  20170915  06:45:53     Bedroom
4        3089  20170915  06:46:09     Outdoor
...       ...       ...       ...         ...
58628    2138  20181202  17:39:27     Kitchen
58629    2138  20181202  20:09:08     Bedroom
58630    2138  20181202  20:21:52     Kitchen
58631    2138  20181203  06:46:44  Livingroom
58632    2138  20181205  10:36:16     Kitchen

[46787 rows x 4 columns]

In [15]:
# filter dataframe for specific 4 places
df = df[df.room.isin(['Bedroom', 'Bathroom', 'Livingroom', 'Kitchen'])]

#group by patient and place
df_time_spent = df.groupby(['part_id', 'room']).size()

#create a new dataframe with total time spent by each patient
df_total_time = df_time_spent.groupby(level=0).sum()

# Divide the time spent in each room by the total time spent to get the percentage
df_percentage = df_time_spent.div(df_total_time, level=0)

# Print the resulting DataFrame
print(df_percentage)

part_id  room
1001     Bathroom      0.140187
         Bedroom       0.177570
         Kitchen       0.299065
         Livingroom    0.383178
1003     Bathroom      0.275000
                         ...
3601     Livingroom    0.118959
3611     Bathroom      0.106007
         Bedroom       0.349823
         Kitchen       0.356890
         Livingroom    0.187279
Length: 950, dtype: float64

In [16]:
df['part_id'] = pd.to_numeric(df['part_id'], downcast='integer')

In [17]:
# Use the `merge()` function to combine the dataframes on the 'part_id' column
merged_df = pd.merge(clinical_df, df, on='part_id')

# Print the resulting DataFrame
print(merged_df)

       part_id  fried  gender  age  hospitalization_one_year  \
0         1001      0       1   75                         0
1         1001      0       1   75                         0
2         1001      0       1   75                         0
3         1001      0       1   75                         0
4         1001      0       1   75                         0
...        ...    ...     ...  ...                       ...
33280     3611      0       1   70                         0
33281     3611      0       1   70                         0
33282     3611      0       1   70                         0
33283     3611      0       1   70                         0
33284     3611      0       1   70                         0

       hospitalization_three_years  ortho_hypotension  vision  audition  \
0                              0.0                  0       1         2
1                              0.0                  0       1         2
2                              0.0                  0       1         2
3                              0.0                  0       1         2
4                              0.0                  0       1         2
...                            ...                ...     ...       ...
33280                          0.0                  0       2         2
33281                          0.0                  0       2         2
33282                          0.0                  0       2         2
33283                          0.0                  0       2         2
33284                          0.0                  0       2         2

       weight_loss  ...  smoking  alcohol_units  katz_index  iadl_grade  \
0              0.0  ...      0.0           1.00         6.0        31.0
1              0.0  ...      0.0           1.00         6.0        31.0
2              0.0  ...      0.0           1.00         6.0        31.0
3              0.0  ...      0.0           1.00         6.0        31.0
4              0.0  ...      0.0           1.00         6.0        31.0
...            ...  ...      ...            ...         ...         ...
33280          0.0  ...      0.0           5.25         6.0        31.0
33281          0.0  ...      0.0           5.25         6.0        31.0
33282          0.0  ...      0.0           5.25         6.0        31.0
33283          0.0  ...      0.0           5.25         6.0        31.0
33284          0.0  ...      0.0           5.25         6.0        31.0

       comorbidities_count  comorbidities_significant_count medication_count  \
0                        5                                0                5
1                        5                                0                5
2                        5                                0                5
3                        5                                0                5
4                        5                                0                5
...                    ...                              ...              ...
33280                    1                                0                1
33281                    1                                0                1
33282                    1                                0                1
33283                    1                                0                1
33284                    1                                0                1

        ts_date   ts_time        room
0      20171209  09:29:56  Livingroom
1      20171209  09:29:59     Kitchen
2      20171209  09:30:35  Livingroom
3      20171209  09:30:46  Livingroom
4      20171209  09:30:50  Livingroom
...         ...       ...         ...
33280  20180914  06:26:46     Kitchen
33281  20180914  06:27:58    Bathroom
33282  20180914  06:30:25     Bedroom
33283  20180914  06:49:49     Bedroom
33284  20180914  06:56:55     Kitchen

[33285 rows x 58 columns]